### PR TITLE
Update Package@swift-5.5.swift

### PR DESCRIPTION
**Pull request by compnerd**
Pin SwiftSemantics to main.  This is required since the 0.3.1 release of SwiftSemantics pins SwiftSyntax to 4ae758ab85ed2a5d3e3e8b5050a8ce52179bd102 and SwiftSyntaxHighlighter requires release/5.5.  In order to restore the ability to resolve the dependencies, we need to bump SwiftSemantics to main.

### CODE REVIEW

**Comment by compnerd** [comment]
@mattt - I suppose that an alternative would be to bump Semantics to 0.3.2 after rolling another release?

**Comment by mattt** [comment]
@compnerd I just released SwiftSemantics 0.3.2, which targets swift-syntax release/5.5. My latest commit here (76679a3) pins to that version. I'm going to see if I can retarget #269 to this branch and rebase to pick up these changes (rather than merge this into main first and hope that CI passes).

**Comment by compnerd** [comment]
Running that locally I see:
```
PS S:\SourceCache\swift-doc> swift package resolve
Updating https://github.com/apple/swift-syntax.git
Updated https://github.com/apple/swift-syntax.git (1.06s)
Updating https://github.com/NSHipster/SwiftSyntaxHighlighter.git
Updated https://github.com/NSHipster/SwiftSyntaxHighlighter.git (0.63s)
Updating https://github.com/SwiftDocOrg/swift-cmark.git
Updating https://github.com/NSHipster/HypertextLiteral.git
Updating https://github.com/SwiftDocOrg/SwiftSemantics.git
Updated https://github.com/SwiftDocOrg/SwiftSemantics.git (0.72s)
Updated https://github.com/SwiftDocOrg/swift-cmark.git (0.72s)
Updated https://github.com/NSHipster/HypertextLiteral.git (0.72s)
Updating https://github.com/SwiftDocOrg/CommonMark.git
Updating https://github.com/SwiftDocOrg/Markup.git
Updating https://github.com/SwiftDocOrg/GraphViz.git
Updated https://github.com/SwiftDocOrg/GraphViz.git (0.58s)
Updating https://github.com/apple/swift-argument-parser.git
Updated https://github.com/SwiftDocOrg/CommonMark.git (0.58s)
Updated https://github.com/SwiftDocOrg/Markup.git (0.58s)
Updating https://github.com/apple/swift-log.git
Updating https://github.com/NSHipster/swift-log-github-actions.git
Updated https://github.com/apple/swift-log.git (0.60s)
Updating https://github.com/SwiftDocOrg/SwiftMarkup.git
Updated https://github.com/apple/swift-argument-parser.git (0.60s)
Updated https://github.com/NSHipster/swift-log-github-actions.git (0.60s)
Updated https://github.com/SwiftDocOrg/SwiftMarkup.git (0.53s)
Computing version for https://github.com/apple/swift-argument-parser.git
Computed https://github.com/apple/swift-argument-parser.git at 0.3.2 (0.09s)
Computing version for https://github.com/NSHipster/swift-log-github-actions.git
Computed https://github.com/NSHipster/swift-log-github-actions.git at 0.0.1 (0.07s)
Computing version for https://github.com/apple/swift-log.git
Computed https://github.com/apple/swift-log.git at 1.4.2 (0.07s)
Computing version for https://github.com/SwiftDocOrg/Markup.git
Computed https://github.com/SwiftDocOrg/Markup.git at 0.1.2 (0.10s)
Computing version for https://github.com/NSHipster/HypertextLiteral.git
Computed https://github.com/NSHipster/HypertextLiteral.git at 0.0.2 (0.07s)
Computing version for https://github.com/SwiftDocOrg/GraphViz.git
Computed https://github.com/SwiftDocOrg/GraphViz.git at 0.4.1 (0.07s)
Computing version for https://github.com/SwiftDocOrg/SwiftMarkup.git
Computed https://github.com/SwiftDocOrg/SwiftMarkup.git at 0.3.0 (0.10s)
Computing version for https://github.com/SwiftDocOrg/CommonMark.git
Computed https://github.com/SwiftDocOrg/CommonMark.git at 0.5.0 (0.08s)
Computing version for https://github.com/SwiftDocOrg/SwiftSemantics.git
Computing version for https://github.com/SwiftDocOrg/SwiftSemantics.git
error: Dependencies could not be resolved because root depends on 'SwiftSemantics' 0.3.2..<0.4.0.
'SwiftSemantics' >= 0.3.2 cannot be used because package 'swiftsemantics' is required using a stable-version but 'swiftsemantics' depends on an unstable-version package 'swift-syntax' and no versions of 'SwiftSemantics' match the requirement 0.3.3..<0.4.0.
```

**Comment by compnerd** [comment]
#279 has this change integrated into it as well.  It probably makes sense to squash and merge this, and then merge main into #279 and then merge that.

**Review by mattt — APPROVED** [review]

**Pull request merged**
