### PR TITLE
Reimplement base URL support without <base> tag

### PR DESCRIPTION
**Pull request by mattt**
This PR seeks to reimplement base URL support added in #65 based on feedback from #82. With my sincere apologies to @kean for leading him down the wrong path by advocating for `<base>` without being aware of its limitations.

I fully acknowledge the jankiness of this approach. Tacking on parameters all over the place like this is unsustainable, but I want to get a fix out sooner rather than later. Long-term, this is the kind of configuration I'd like to encapsulate by a `Generator` (#67)

### CODE REVIEW

**Comment by kean** [comment]
Hey, @mattt. Thanks for addressing this. I was going to work on it, but I've been sick for the past two weeks.

**Comment by kean** [comment]
@mattt , CSS also needs to use base-url. Currently it is not working when deployed in non-root folder.

```
<link rel="stylesheet" type="text/css" href="/all.css" media="all" />
```

**Comment by kean** [comment]
Hmm, it seems swift-doc also used --base-url as an output path which was unexpected and I had to fix manually.

Screen Shot 2020-04-27 at 18 02 58

**Comment by kean** [comment]
Ah, I see, the expectation is to put a single all.css in my root directory? I could do that, but I'm not sure how well it's going to work with my personal workflow. I deploy documentation once per version and then never touch it again. This isn't going to work if all.css file keeps changing with potentially breaking changes to the previously generated documentation.

**Comment by mattt** [comment]
> Hmm, it seems swift-doc also used --base-url as an output path which was unexpected and I had to fix manually.

That's definitely a bug. Thanks for pointing that out.

> Ah, I see, the expectation is to put a single all.css in my root directory? I could do that, but I'm not sure how well it's going to work with my personal workflow. I deploy documentation once per version and then never touch it again. This isn't going to work if all.css file keeps changing with potentially breaking changes to the previously generated documentation.

The idea is for `swift doc generate` to create a "bundle", such that everything within that bundle is  sealed and self-sufficient. There may be changes in the DOM or CSS between releases that change appearance, but any generated output will be inert and unaffected by any such changes.

**Pull request merged**
