### PR TITLE
Add graphviz in Dockerfile

### PR DESCRIPTION
**Pull request by MaxDesiatov**
`graphviz` is not currently installed, which triggers warnings when running the corresponding GitHub Action.

### CODE REVIEW

**Review by mattt — APPROVED** [review]

**Comment by mattt** [comment]
Thanks for the PR, @MaxDesiatov. I would have sworn that this was already in there, but I'm probably conflating adding GraphViz as a dependency in the Homebrew formula. Anyway, glad to have this fixed, and looking forward to having this available in the forthcoming release.

**Comment by MaxDesiatov** [comment]
Thanks, I also have a prebuilt image here that I'm using in the meantime to make the action run faster, just in case you're interested https://hub.docker.com/r/maxdesiatov/swift-doc

I hope you could upload the official one in your Docker Hub namespace at some point.

**Comment by MaxDesiatov** [comment]
(This required me to create two separate Dockerfiles in my swift-doc fork, one for the prebuilt image, the other for the action that only references the prebuilt image and does nothing else)

**Comment by mattt** [comment]
@MaxDesiatov

> Thanks, I also have a prebuilt image here that I'm using in the meantime to make the action run faster, just in case you're interested https://hub.docker.com/r/maxdesiatov/swift-doc
> 
> I hope you could upload the official one in your Docker Hub namespace at some point.

That's great! Let's continue this discussion on #111.

**Pull request merged**
